config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :users do
  #   resources :gyms do
  #     resources :posts do
  #       resources :comments
  #     end
  #   end
  # end

  resources :posts do
    resources :comments
  end
resources :gyms

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :posts
  has_many :users
  validates :name, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def new
  @post = Post.find(params[:post_id])
end
def create
  @post = Post.find(params[:post_id])
  @comment = @post.comments.create(params[:comment].permit(:name, :body))
  if @comment.save
    redirect_to post_path(@post)
  else
    redirect_to post_path(@post)
    flash[:error] = "Fill in comment body"
  end
end
def destroy
  @post = Post.find(params[:post_id])
  @comment = @post.comments.find(params[:id])
  @comment.destroy
  redirect_to post_path(@post)
end
def index
  @posts = Post.all
  @comments = @post.comments.paginate(page: params[:page])
end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  def index
    @gyms = Gym.all
  end
  def new
    @gym = Gym.new
  end
  def show
    @gym = Gym.find(params[:id])
  end
  def create
    @gym = Gym.new(gym_params)
    if @gym.save
      redirect_to @gym
    else
      render "new"
    end
  end
  def edit
  end
  def destroy
  end

private
  def gym_params
    params.require(:gym).permit(:name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
def index
  @posts = Post.paginate(:page => params[:page], :per_page => 10)
  # @posts = Post.all.order('created_at DESC')
end
def new
  @post = Post.new
end
def create
  @post = current_user.posts.new(post_params)
  if @post.save
    redirect_to @post
  else
    render "new"
  end
end
def show
  @post = Post.find(params[:id])
  @comments = @post.comments.paginate(page: params[:page], :per_page => 1)
end
def edit
  @post = Post.find(params[:id])
end
def update
  @post = Post.find(params[:id])
  if @post.update(params[:post].permit(:title, :body))
    redirect_to @post
  else
    render "edit"
  end
end
def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to root_path
end
private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class ="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> old
    <% if (user_signed_in? && (current_user.id == @post.user_id))%>
    <%= link_to "Delete", [comment.post, comment],
            method: :delete,
            class: "button",
            data: {confirm: 'Are you sure?'} %>
    <% end %>
    </p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<% if @post.errors.any? %>
  <div id="errors">
      <h1><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h1>

        <% @comment.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>

    </div>
<% end %>

<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %><%= f.submit %>
</p>

<% end %>

app/views/comments/_new.html.erb
<%= render 'form' %>

app/views/gyms/index.html.erb
<button><%= link_to "New Gym", new_gym_path %></button>
<% @gyms.each do |gym| %>
  <div class ="gym_wrapper">
    <h2 class ="name"><%= link_to gym.name, gym %></h2>
  </div>
  <% end %>

app/views/gyms/new.html.erb
New Gym
<%= form_for :gym, url: gyms_path do |f| %>
<% if @gym.errors.any? %>
  <div id="errors">
      <h1><%= pluralize(@gym.errors.count, "error") %> prevented this post from saving</h1>

        <% @gym.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      
    </div>
<% end %>
<p>
<%= f.label :name %> <br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :body %><br>
<%= f.text_area :body %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/gyms/show.html.erb
<h2 class ="title"><%= @gym.name %></h2><br>
<%= @gym.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RacquetballRi</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="signInLinks">
      <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %>
    <%= link_to 'View Profile', current_user, :class => 'navbar-link' %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

    </div>
    <div class ="yields"><%= yield %></div>
    <ul>
        <li class="animated infinite pulse"><%= link_to "All Posts", root_path %></li>
        <li class="animated infinite pulse"><%= link_to "Gyms in RI", gyms_path %></li>
        <li class="animated infinite pulse"><%= link_to "Players of RI", users_path %></li>
    </ul>
<div class="flexbox">
    <div id="ri">Rhode Island Racquetball</div>
</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
  <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><% msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<p>
<%= f.label :title %> <br>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :body %><br>
<%= f.text_area :body %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/posts/edit.html.erb
<h2> edit post </h2>
<% if (user_signed_in? && (current_user.id == @post.user_id))%>
<%= render 'form' %>
<% else flash.alert = "You must be the owner of this post to edit" %>
<% end %>

app/views/posts/index.html.erb
<div class ="animated bounce" ><%= link_to "New Post", new_post_path %></div>
<% @posts.each do |post| %>
  <div class ="post_wrapper">
    <div id="ballAndTitle">
      <img id="racquetball" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Racquetball_ball.svg" alt="image should be here" />
      <h2 class ="title"><%= link_to post.title, post %></h2>
    </div>
    <p class ="date"><%= post.user.email %> Posted :<%= post.created_at.strftime("%B, %d, %Y")%></p>
  </div>
  <% end %>
  <div class="digg_pagination">
    <div class="page_info">
      <a href="http://s524.photobucket.com/user/razhbi/media/bounce_147.gif.html" target="_blank"><img id="bouncingBall" src="http://i524.photobucket.com/albums/cc329/razhbi/bounce_147.gif" alt=" photo bounce_147.gif"/></a><%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, :container => false %>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
  <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </ul>
    </div>
<% end %>
<p>
<%= f.label :title %> <br>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :body %><br>
<%= f.text_area :body %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/posts/show.html.erb
<h2 class="title">
  <%= @post.title %><br>
  <%= @post.user.email %>
</h2>

<p class = "date">
  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
  <% if (user_signed_in? && (current_user.id == @post.user_id))%>
  | <%= link_to 'Edit', edit_post_path(@post) %>
  | <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
</p>

<p class= "body">
  <%= @post.body %>
</p>

<div id="comments">
  <h2><%= @post.comments.count %> Comments</h2>
  <% @comments.each do |comment| %>
    <div class ="post_wrapper">
      <h2 class ="name"><%= render comment %></h2>
    </div>
    <% end %>
  <%= will_paginate @comments %>
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @comments %>
    </div>
    <%= will_paginate @comments, :container => false %>
  </div>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %>
<% if (user_signed_in?)%>
  <h3>Add a comment</h3>
  <%= render "comments/form" %>
</div>

<% end %>

app/views/users/index.html.erb
<div id="playersIndexTitle">The players of RI</div>
<% @users.each do |user| %>
  <div class ="post_wrapper">
    <h2 class ="title"><%= link_to user.email, user %></h2>
  </div>
  <% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1><br>
<% @user.posts.each do |post| %>
 <div id="profileTitleStyle"><%= link_to post.title, post %></div>
 <% if (user_signed_in? && (current_user.id == post.user_id))%>
 | <%= link_to 'Edit', edit_post_path %>
 | <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
 <% end %>
 <br>
<% end %>